[package]
name = "blockp2p"
version = "0.1.0"
description = "Fast blockchain broadcast with scalable p2p network topology"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
edition = "2021"

[dependencies]
bincode = "1.3.3"
blake2b_simd = "1"
bls-signatures = "0.13.0"
bytebuffer = "2.0.1"
hex = "0.4.3"
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.38"
